name: ArXiv Daily V2

on:
  # 定时触发
  schedule:
    # 每天UTC时间10:00（北京时间18:00）执行
    - cron: '0 10 * * *'
  # 手动触发
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.8" # set this to the Python version to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run_arxiv_daily:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置Python环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 执行脚本
      - name: Run arxiv.py
        env:
          # 可配置的环境变量
          FEISHU_URL: ${{ secrets.FEISHU_URL }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          # 目标分类，使用逗号分隔的字符串格式
          TARGET_CATEGORYS: "cs.IR,cs.CL,cs.CV"
          # 最大论文数量
          MAX_PAPERS: "100"
          # 粗排分数阈值
          ROUGH_SCORE_THRESHOLD: "4"
          # 返回论文数量
          RETURN_PAPERS: "20"
        run:
          python -m paperBotV2.arxiv

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)" ]; then
             echo "::set-output name=push::false"
          else
             git commit -m "chore: update arxiv papers" -a
             echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}