name: update_content

env:
  PYTHON_VERSION: "3.8" # set this to the Python version to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  issues:
    types:
      - labeled

jobs:
  update-conf-list:
    if: github.event.label.name == 'require to update content'
    runs-on: ubuntu-latest
    env:
      FEISHU_URL: ${{ secrets.FEISHU_URL }}
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update the cache file from the issue
        run: python paperBotV2/industry_practice/maintain.py --issue ${{ toJson(github.event.issue.body) }}
        
        
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "chore: update content" -a
             echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false

      - name: Deploy to GitHub Pages
        if: steps.commit.outputs.push == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./paperBotV2/industry_practice/output
          destination_dir: industry_pratice
          publish_branch: gh-pages
          force_orphan: false
          keep_files: false
